<a href="https://colab.research.google.com/github/berfino/PizzaOrder_bootcamp/blob/main/NumPy02_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

##0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.


In [38]:
np.arange(0,30).reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

##60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.



In [39]:
array = np.random.randint(10,100,60)
array

array([39, 58, 33, 58, 50, 47, 69, 56, 17, 30, 29, 64, 25, 85, 81, 47, 41,
       42, 19, 45, 30, 61, 13, 61, 64, 19, 56, 36, 59, 14, 15, 95, 37, 98,
       22, 36, 15, 85, 66, 76, 22, 92, 37, 69, 55, 85, 65, 90, 99, 11, 16,
       60, 53, 62, 28, 78, 73, 63, 10, 86])

In [18]:
arr3d = array.reshape(2,2,-1)
arr3d

array([[[14, 29, 52, 88, 11, 95, 50, 39, 67, 93, 27, 22, 48, 22, 82],
        [33, 55, 29, 14, 43, 69, 80, 43, 38, 29, 76, 71, 22, 22, 11]],

       [[50, 50, 76, 67, 13, 21, 32, 35, 48, 15, 59, 72, 79, 81, 57],
        [81, 37, 45, 90, 65, 53, 45, 26, 73, 61, 83, 89, 23, 16, 34]]])

In [19]:
arr3d.ndim

3

In [40]:
arr3d.shape

(2, 2, 15)

##20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.


In [29]:
arr2d = np.random.randint(0,10,size=(2,10))
arr2d

array([[5, 3, 0, 7, 3, 3, 2, 0, 0, 4],
       [4, 3, 5, 9, 2, 9, 1, 4, 0, 0]])

In [35]:
arr = arr2d.reshape(-1)
arr

array([5, 3, 0, 7, 3, 3, 2, 0, 0, 4, 4, 3, 5, 9, 2, 9, 1, 4, 0, 0])

In [36]:
arr.ndim

1

In [37]:
arr.shape

(20,)

##İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.


In [42]:
arr2d = np.random.randint(10,30,size=(5,6))
arr2d

array([[10, 21, 22, 26, 18, 17],
       [11, 23, 24, 28, 24, 19],
       [24, 12, 28, 20, 14, 24],
       [28, 26, 19, 20, 21, 20],
       [25, 11, 23, 22, 19, 17]])

In [43]:
for i in arr2d:
  for x in i:
    print(x)

10
21
22
26
18
17
11
23
24
28
24
19
24
12
28
20
14
24
28
26
19
20
21
20
25
11
23
22
19
17


In [44]:
for i in np.nditer(arr2d):
  print(i)

10
21
22
26
18
17
11
23
24
28
24
19
24
12
28
20
14
24
28
26
19
20
21
20
25
11
23
22
19
17


##5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve 1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.

In [48]:
arr1 = np.arange(5,31,5)
arr1

array([ 5, 10, 15, 20, 25, 30])

In [52]:
arr2 = np.arange(1,7)
arr2

array([1, 2, 3, 4, 5, 6])

In [56]:
arr1[1].__add__(arr2[1])

12

In [57]:
np.add(arr1[1],arr2[1])

12

In [59]:
arr[1].__sub__(arr2[1])

8

In [60]:
arr[1].__mul__(arr2[1])

20

In [64]:
arr[1]/arr2[1]

5.0

In [66]:
np.divide(arr1[1],arr2[1])

5.0

##0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.


In [67]:
arr = np.random.randint(0,100,10)
arr

array([92, 39, 15, 54, 95, 81, 92, 54,  6, 65])

In [68]:
arr.sum()

593

In [69]:
arr.mean()

59.3

In [72]:
arr.max()

95

In [73]:
arr.min()

6

In [74]:
arr.var()

918.8100000000001

In [75]:
arr.std()

30.31187885961542

##0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.


In [77]:
arr1 = np.arange(0,20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [78]:
arr2 = np.arange(500,531)
arr2

array([500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512,
       513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530])

In [79]:
np.concatenate([arr1,arr2], axis=0)


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

## 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.


In [82]:
arr1 = np.arange(15,51)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50])

In [83]:
arr2 = np.arange(10,101)
arr2

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [85]:
arr3 = np.concatenate([arr1,arr2], axis=0)
arr3

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [89]:
arr3[25:51] = 888
arr3

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

##0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.


In [91]:
arr1 = np.arange(0,40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [92]:
arr2 = np.arange(320,360).reshape(8,5)
arr2

array([[320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [93]:
arr3 = np.concatenate([arr1,arr2], axis=0)
arr3

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [94]:
arr3 = np.concatenate([arr1,arr2], axis=1)
arr3

array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

### 9. soru açıklama : concatenate işlemini axis = 1 ve axis = 0 işlemlerini uyguladığımızda axis = 0 işleminde arrayleri alt alta birleştirirken, axis = 1 işleminde arrayleri indexleri yanyana birleştirme işlemi yapmıştır. 

## 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.


In [95]:
arr3 = np.concatenate([arr1,arr2], axis=2)
arr3

AxisError: ignored

In [97]:
arr3 = np.stack([arr1,arr2],axis=2)
arr3

array([[[  0, 320],
        [  1, 321],
        [  2, 322],
        [  3, 323],
        [  4, 324]],

       [[  5, 325],
        [  6, 326],
        [  7, 327],
        [  8, 328],
        [  9, 329]],

       [[ 10, 330],
        [ 11, 331],
        [ 12, 332],
        [ 13, 333],
        [ 14, 334]],

       [[ 15, 335],
        [ 16, 336],
        [ 17, 337],
        [ 18, 338],
        [ 19, 339]],

       [[ 20, 340],
        [ 21, 341],
        [ 22, 342],
        [ 23, 343],
        [ 24, 344]],

       [[ 25, 345],
        [ 26, 346],
        [ 27, 347],
        [ 28, 348],
        [ 29, 349]],

       [[ 30, 350],
        [ 31, 351],
        [ 32, 352],
        [ 33, 353],
        [ 34, 354]],

       [[ 35, 355],
        [ 36, 356],
        [ 37, 357],
        [ 38, 358],
        [ 39, 359]]])

### Axis = 2 işleminde concatenate işlemi yapılmamaktadır sebebi ise arrayimizin 2 boyutlu olmasıdır. stackleme işleminde her iki arrayin indexlerini karşılıklı olarak alıyor ve yeni indexler oluşturuyor. 

## [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.


In [100]:
arr = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
arr

array([ 1, 20, 25,  4,  4,  5,  4,  4,  1,  6,  9, 12,  1,  5])

In [103]:
np.where(arr == 5)

(array([ 5, 13]),)

## Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.

In [105]:
np.where(arr%2 == 0)[0]

array([ 1,  3,  4,  6,  7,  9, 11])

##  Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.

In [110]:
np.where(arr> 4)


(array([ 1,  2,  5,  9, 10, 11, 13]),)

## Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.


In [109]:
np.where(arr%5 == 0)


(array([ 1,  2,  5, 13]),)

## 85-100(100 dahil) arasından rastgele 1 tam sayı seçin


In [111]:
np.random.randint(85,101)

99

##İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.

In [113]:
arr = np.random.randint(10,100,size=(3,3))
arr

array([[66, 62, 79],
       [89, 13, 51],
       [91, 27, 73]])

## 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.

In [115]:
arr = np.arange(35,60)
arr

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59])

In [116]:
np.random.choice(arr)

46

##  Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

In [119]:
arr = np.random.choice([3, 8, 10, 53], size=(2, 5))
arr

array([[ 8, 53, 10, 10,  3],
       [53,  3,  8, 53, 53]])

In [121]:
#Done.:)